# Generated by Django 2.0.4 on 2018-05-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=500)),
                ('objtext', models.TextField(max_length=5000)),
                ('objectives', models.TextField(max_length=5000)),
                ('listheader', models.CharField(max_length=100)),
                ('listcontent', models.TextField(max_length=5000)),
                ('target', models.CharField(max_length=500)),
                ('cost', models.CharField(max_length=500)),
                ('dates', models.DateTimeField()),
            ],
        ),
    ]
