# Generated by Django 2.0.4 on 2018-05-18 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('objtext', models.TextField(max_length=5000, null=True)),
                ('objectives', models.TextField(max_length=5000, null=True)),
                ('listheader', models.CharField(max_length=100, null=True)),
                ('target', models.CharField(max_length=500, null=True)),
                ('cost', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listcontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_id', models.CharField(default=None, max_length=200)),
                ('listcontent_text', models.TextField(max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sublistcontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sublistcontent_text', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='listcontent',
            name='sublistcontent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.Sublistcontent'),
        ),
        migrations.AddField(
            model_name='course',
            name='listcontent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.Listcontent'),
        ),
    ]
